modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="create_compact_transmission"
version="1.0.0"
displayName="Create: Compact Transmission"
logoFile="logo.png"
authors="Chelovechic_(Github)"
description='''Compact blocks for Create'''

[[dependencies.create_compact_transmission]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.create_compact_transmission]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.create_compact_transmission]]
modId="create"
mandatory=true
versionRange="[6.0.8,)"
ordering="AFTER"
side="BOTH"
